
default: &default
  adapter: postgresql
  encoding: unicode
  username: eio
  password: eio
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: eio

test:
  <<: *default
  database: eio


production:
  <<: *default
  database: eio
